### ISSUE TITLE
After upgrade or installing version 1.5.1 no button to creat label on the order page

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#132]
### Module version

1.5.1

### PrestaShop version

1.7.8.3 and 1.7.8.5

### PHP version

7.4

### What went wrong?

Upgrade to 1.5.1. will not create button inline of the orderpage in the backoffice.
creat webhook, empty cache no help.
installed the version on an fresh Prestshop installation also no buttons on the order page.

### Reproduction steps

1. Navigate to order page in the back-office
2. Click on orders and or order details
3. See no buttons to creat labels

**Comment by Mouzarty** [comment]
Same issue.....

**Comment by RichardPerdaan** [comment]
Hi @Frankyet and @Mouzarty ,

Thank you for sharing your issue.
Unfortunately we cannot reproduce this problem, but we would like to solve this problem.

Could you send an email to support@myparcel.nl. Then it will be possible for us to see te problem and can we make the solution faster.

**Comment by rockincent** [comment]
Same issue

**Comment by EdieLemoine** [comment]
@Frankyet @Mouzarty @rockincent 

As we cannot reproduce this, could you please share some more information?

- Are you running your website in a subfolder? (e.g. `mywebsite.com/folder/` instead of just `mywebsite.com`.) If so, this will be fixed by #134, which will be released next week.

If not, please share the following:
- Which browser you're using
- All errors/messages you see in the "Console" tab of your browser's inspector.
- All errors in the "Network" tab of the inspector.

If you're not familiar with the inspector, here are some instructions:

- [Chrome/Chromium](https://developer.chrome.com/docs/devtools/open)
- [Safari](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/Web_Inspector_Tutorial/EnableWebInspector/EnableWebInspector.html)
- [Firefox](https://firefox-source-docs.mozilla.org/devtools-user/index.html)

Thanks!

**Comment by Frankyet** [comment]
I have an test shop in a folder that is correct.
I have tried to implement fix #134 but I found that the folder js is missing, there is no js folder in the zip file 1.5.1 as well 1.5.2 but if you download the Source code (zip) there is the folder js, Is this correct?

![image](https://user-images.githubusercontent.com/22242384/163632055-a15eb275-8a68-4e06-9909-c9ebb0747bb2.png)

**Comment by EdieLemoine** [comment]
This probably does not happen anymore in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version. If it still occurs, please feel free to open a new issue.
