### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by dtccomputers** [myparcelnl/prestashop#177]
### Module version

1.6.2

### PrestaShop version

1.7.8.6

### PHP version

7.3.33

### What went wrong?

When opening one specific order, no myparcel tab is loaded. 
Chrome Devtools is giving me a "Uncaught SyntaxError: missing ) after argument list (at" https://dtccomputers.nl/xxxxxx/index.php/sell/orders/1003/view?_token=-xxxxxx:2660:28

This is leading me to 

  var context = JSON.parse**(**'{"errors":[],"returnsForm":{"name": (customer data)

### Reproduction steps

This happens only at this specific order. The next order is functioning fine. 
I can create a label from the front page, but not from the detailed page.

Hoping someone can help me out. 

### Relevant log output

```shell
Got error 'Primary script unknown'
```

**Comment by RichardPerdaan** [comment]
Hi @dtccomputers ,

Thank you for posting your message. 
When I look at the code, I don't see the problem.

I think this problem may be related to something else. 
The reason I think this is because you don't have this problem with other orders.

I expect that you will see several errors in the console, which will lead you to the correct problem.

I don't think we can solve this for you.
This is why I will close this issue
