### ISSUE TITLE
Uploading 1.0.2 gives error

### ISSUE THREAD

**Issue by folkertsmit** [myparcelnl/prestashop#21]
When installing 1.0.2 i the installaion fais. Either using the zip or unpack and upload to modules folder.

Trying installed 1.0.1 did work

ps 1.7.4.3

**Comment by Mitchell-MyParcel** [comment]
@folkertsmit: I haven't spotted this before, but now I also see the same version number mentioned in the case that you sent us. I assumed (wrongly) you were using ps 1.7.7.3 instead of 1.7.4.3 but you clearly stated otherwise. My apologies. 

We cannot guarantee the correct functionality of the new plugin on this older version of Prestashop. With time I strongly suggest upgrading your Prestashop but for now you could try installing an older version of our plugin:

https://github.com/myparcelnl/prestashop-deprecated/releases/tag/v2.3.8
