### ISSUE TITLE
Can you PLEASE create a WORKING module for once

### ISSUE THREAD

**Issue by Multipage** [myparcelnl/prestashop#46]
Hi,

Shame on you! We have multiple customers working with MyParcel who experience problems. HUGE problems and the attitude of you is "Oh well and then go to sleep again".
Even support engineers don't respond anymore! That's why i post here!

FIX your problems. This module could be fixed in a day or 10 WHY MONTHS and STILL nothing but more s**t. It's pathetic!
We have 150+ websites. 
People can't stay on Prestashop <1.7.7.1 for ever just because you dont have your .... together. 
Try getting some experienced devs on board. 
Give us a date for the working,TESTED and USABLE module!

We've had enough of this! 

* When editing a carrier, a new carrier is created( so if you edit a carrier 5 times you get 6 carriers)
* T&T in a customfield instead of the default Prestashop field
* Only 1 carrier can be used if you add another one you can't configure anything anymore
* Carrier costs are incorrect,  0% tax rate ??!?! (wtf?)
* Troubles with labels on Prestashop 1.7.7.3  and up
* Pickup points not in delivery address
* Carrier options not always loaded in Prestashop checkout 1.7.7.5 and up

And maybe there is more but currently it's unusable so we do have to find more bugs.
This shouldn't even be released to the public, it's garbage. Not even Alpha state.

**Comment by rockincent** [comment]
I completely agree. I'm still waiting on a bug free addon. But my waiting is over.
I switched to Sendcloud. Perfect addon and has competitive prices.

**Comment by RichardPerdaan** [comment]
Hi @Multipage,
I am sorry to hear that you are experiencing issues with the MyParcel PrestaShop plugin.
We are working every day to improve the plugins, including the PrestaShop plugin.
The problems have been noted.

**Comment by Multipage** [comment]
Hi @RichardPerdaan,

It's very hard to believe the Prestashop Plugin gets the same (serious) attention as other plugins.
Even when people complain and openly criticize it your reaction is :"The problems have been noted." and then back to sleep i think. Once again ...no serious actions have been taken.
You can't even imagine the problems your customers are having with this s*** plugin and as you reaction reads between the lines there is no intention of MyParcel to fix this any time soon.

IF it's true your working hard and everyday on this module...please fire the developers.As a developer: If i released this s*** code and couldn't fix it in almost a year i would've been fired on the spot and needless to say; That would be deserved!

What i think you are doing is waiting for the community to fix your problems because you( MyParcel) are incapable to fix it.
The problems are stacking up and you are always 20 steps behind, hands on fixing bugs and developing is absent. There is nobody at MyParcel to test the module in newer versions Prestashop so people who update Prestashop and run into problem with this s*** module are ...... ( not writing the  word, fill in the blanks). How hard is it to test with a beta version of Prestashop just to test the compatibility and already create some fixes if it isn't compatible.

Sure, i could fix a lot of your problems within days. On my own...but why can i ..and you can't! Assuming you have a dev team, which i highly doubt it. And why should i? And do this for free anyway! You are making lots of money, your customer pays you for your services ...and you're giving them absolutely nothing but troubles ...... and really bad support on this.
I'm not giving you free code/fixes because of this and the attitude of MyParcel.

If the devs give this plugin the attention it needs for a week or 2 all problems could be fixed and you have happy customers. 
Why the wait !!! Action is required, NOW!

**Comment by EdieLemoine** [comment]
Hello @Multipage and others,

I completely understand your frustrations. We actually are working as hard as we can on fixing bugs and adding missing features, given our time constraints. 

This plugin was built by an external party, we were not involved with the actual code up until recently. Sadly, it turns out many features don't work properly and the code does not meet our standards, making it hard to fix bugs fast. A lot of love and refactoring is needed to get this plugin to our desired level of quality and stability, which takes a lot of time.

Our plugins team isn't very large at the moment and we have a lot of other work to attend to, especially with the holiday season coming up, we can't just ignore everything else and dive into this plugin for weeks.

This thread does help reinforce the urgency of these issues. We're currently in the final stages of adding two large features to our other plugins, I expect a lot of high priority Prestashop bugs, like these, are waiting for us on the other side. 

P.S. If you ever do change your mind on giving us "free code", you're always welcome to open a pull request. Obviously, that shouldn't be necessary, but if you've found some quick fixes for major issues you're dealing with you would be saving yourself a few more weeks of waiting.

**Comment by Mitchell-MyParcel** [comment]
@Multipage and others. Some of the issues mentioned by you we recognise, others not and could also not be reproduced by us or require more information. Based on your github posts we have tried to find your support case(s) but were not able to find them, so I will place a reaction per issue. I understand that it is annoying to explain every issue again so a reply on a support ticket with a mention to this thread in the reply would also be enough.

> When editing a carrier, a new carrier is created( so if you edit a carrier 5 times you get 6 carriers)

We could not reproduce this issue in v1.2.0 on our own testing environments. Either this is an issue that is triggered by some unique properties of your environment or you are changing some specific setting that triggers this. Either way we would like to have more information.

> T&T in a customfield instead of the default Prestashop field 

We will fix this with high priority.

> Only 1 carrier can be used if you add another one you can't configure anything anymore

We could not reproduce this and will need more information.

> Carrier costs are incorrect, 0% tax rate ??!?! (wtf?)

If we use the native tax setting in the carrier settings the configured tax will be added to both the shipping costs and optional delivery options. We will need more information to debug this.

> Troubles with labels on Prestashop 1.7.7.3 and up

Admittedly there have been a lot of issues with labels but most of these issues should be fixed by know (v1.2.0). There are still some issues that we know of but in order to help you we will need more information.

> Pickup points not in delivery address

Most of our carriers require a home address as delivery address and a separate pick up point address. Hence it is technically undesirable to place the pick up address in delivery address fields. If we could contact you we would gladly look for a solution that works for both of us.

> Carrier options not always loaded in Prestashop checkout 1.7.7.5 and up

This is a known issue and we understand this should be fixed as soon as possible. We will fix this with high priority.

Maybe some of the issues mentioned above are triggered by some specific properties of your environment. In this case the quickest way to fix them is by sending us login details for a testing environment. If you already did this could you please send a reply to that ticket with a mention to this thread (link, title or issue number)?

**Comment by JanMiddelkoop** [comment]
While I don't share the tone & attitude of @Multipage, I do share the feelings. It seems that every new release of the module or new release of PrestaShop brings more new issues in the MyParcel integration. As a fellow developer, I understand that this is not always avoidable. I do think the testing process and especially time for releasing bugfixes could be improved. If a new release brings a regression with it, I'd expect that to be fixed in one or two days at most. Not weeks.

I know my client has also started looking at alternatives to MyParcel for their webshops due to all the issues with the integration.

Which leads me to ask: is this module compatible with PrestaShop 1.7.8? We would like to update the stores shortly.

**Comment by Multipage** [comment]
@JanMiddelkoop my 'tone and attitude' is a result of almost a year hearing lame responses on serious problems, unworkable situations en empty promises. Enough is enough, right? I don't know how far your patience goes on a not working very important functionality for an ecommerce site ;)

Hopefully we are getting a workable solution, decent support and hands on development for future versions of Prestashop by this post. If that's the case then this post did it's job.

I wouldn't install/update it or update Prestashop untill they have fixed all problems and are ready to fix your problems way faster then months...otherwise we will see a same post as mine in about a year from you for sure ;).

**Comment by JanMiddelkoop** [comment]
@Multipage Don't take it personally; it wasn't meant as criticism. Just a subtle reminder that GitHub does have community guidelines. I'll open a seperate issue for the 1.7.8 compatibility question.

**Comment by Mitchell-MyParcel** [comment]
@Multipage: We are grateful for your pull requests and are working on the points we could reproduce. Like mentioned above, we cannot reproduce all issues. So either we are doing something in a different way or these issues are triggered by something specific to your environment. The best way to solve these issues is if we can see them ourselves, preferably by having access to a testing environment but even a remote session would help a lot. Could you please react to an open ticket or contact us by sending an email to support@myparcel.nl and mentioning this thread?

**Comment by Multipage** [comment]
@Mitchell-MyParcel I cannot find any customer who wants to test voluntarily. We've installed/updated 1 customer...and quess what....are you really kidding me?  See my just opened issues...i can find theses bugs in a few minutes time. Something tells me you guys don't test..it's obvious

**Comment by JanMiddelkoop** [comment]
@Multipage For the record, I've had no issues whatsoever with the latest version of the module with PrestaShop 1.7.8. In fact, all issues my customer had were resolved.

**Comment by Mitchell-MyParcel** [comment]
@Multipage We adhere to all testing practises one might expect from us. In our reply from 25oct you can read which issues we could reproduce. These have been fixed in v1.3.0. 

The remaining issues are either the result of specific conditions of your environment or triggered under circumstances unknown to us. We would gladly debug these issues but I cannot stress enough that we require more information to do this. From our experience direct contact is best because debugging might require the exchange of credentials or private info, hence our advice to mail support@myparcel.nl or mentioning this thread in a running case.

We are looking into the 2 issues you just posted.

**Comment by Mitchell-MyParcel** [comment]
All issues in this thread that can be reproduced, have been fixed.
