### ISSUE TITLE
Bug V1.3.0 Prestashop Security update can't be installed because of incompatibility with 1.7.8.2

### ISSUE THREAD

**Issue by Multipage** [myparcelnl/prestashop#98]
This is something we warned about: No we HAVE to update to 1.7.8.2 because of SQL injection security troubles and we can't because the module isn't compatible.

Now...we have a choice..update all shops and say to or customers who are using MyParcel: 'Sorry we can't update because of MyPracel, so if you get hacked ..tough luck'. 
We've choosen to update all our shops....fix the module asap please! And respond to the other issues!

**Comment by Mitchell-MyParcel** [comment]
@Multipage As of now we have no indication that upgrading to v1.7.8.2 is breaking. On our own testing environments (see the screencap below) both checkout and ordergrid functionality are operational even after upgrading. I also checked the logs and no errors are being thrown. Hence there must be plug-ins, settings or code maybe not unique but certainly specific to your environments that are breaking our plug-in. Since this is a security patch we are keen on helping you, but we cannot help you without more information to run on. So again, please contact us on support@myparcel.nl or minimally specify what error   you get and when you are getting it.

https://user-images.githubusercontent.com/69574208/145831760-0bdb9718-4967-4fe7-8622-469166e70387.mov
